# Generated by Django 4.2.7 on 2026-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpost',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carpost',
            name='horsepower',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpost',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpost',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='carpost',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
